### ISSUE TITLE
Stuck on gathering windows

### ISSUE THREAD

**Issue by r3volution11** [alfredapp/window-switcher-workflow#2]
### Workflow version

2022.4

### Alfred version

5.0.6

### macOS version

12.3

### Debugger output

```alfred_debugger
[12:19:37.114] Logging Started...
[12:19:39.243] Window Switcher[Script Filter] Queuing argument '(null)'
[12:20:06.284] Window Switcher[Hotkey] Processing complete
[12:20:06.287] Window Switcher[Hotkey] Passing output '' to Script Filter
```

### More details

When I attempt to run the command it will just sit stating it's gathering windows. Unfortunately, the log doesn't really return anything helpful.

Although when I do attempt to put in a name of a window it appears to still pass as "(null)".

**Comment by vitorgalvao** [comment]
Can you try [this version](https://github.com/alfredapp/window-switcher-workflow/issues/1#issuecomment-1357708122) and report back?

**Comment by r3volution11** [comment]
Same deal. It just sits on:

`[15:41:49.485] Window Switcher[Script Filter] Queuing argument '(null)'`

**Comment by vitorgalvao** [comment]
Closing for lack of follow-up.

**Comment by vitorgalvao** [comment]
@r3volution11 The workflow has been rewritten in Swift, so worth giving it another go. [Download it from the releases](https://github.com/alfredapp/window-switcher-workflow/releases/tag/2023.1), I’d be interested to know how it behaves on Monterey.

**Comment by r3volution11** [comment]
Boom shakalaka! 

I think the issue may have been that Alfred didn't have screen recording permissions. I don't recall seeing that was required beforehand but noticed the helpful message when I first tried to run the workflow again.

And sorry about not following up previously.
