### ISSUE TITLE
does it not show show minimized or hidden windows? 

### ISSUE THREAD

**Issue by zeltak** [alfredapp/window-switcher-workflow#6]
### Workflow version

2023.8

### Alfred version

5.1.3

### macOS version

Sonoma

### Debugger output

```alfred_debugger
Hi, is this by design or does it not show show minimized or hidden windows? 

maybe im missing something? didn't see any setting options for that?

thx so much for this great addition

Z
```

### More details

Hi, is this by design or does it not show show minimized or hidden windows? 

maybe im missing something? didn't see any setting options for that?

thx so much for this great addition

Z

**Comment by vitorgalvao** [comment]
[It’s by design](https://www.alfredforum.com/topic/17665-window-switcher-—-switch-to-a-specific-window-of-an-app-in-the-current-desktop-space/#comment-91325).

**Comment by zeltak** [comment]
thx for the prompt response @vitorgalvao 

may I as why? and would you consider a feature request to perhaps add an option to show hidden windows as well

kind regards 

Z

**Comment by vitorgalvao** [comment]
All those questions are answered in the linked post.
