### ISSUE TITLE
It would be neat if windows were ordered in the order of last active window.

### ISSUE THREAD

**Issue by adamnemecek** [alfredapp/window-switcher-workflow#8]
### Feature details

I realize that this might require a daemon to run to observe the switches. Maybe this can be integrated into Alfred?

**Comment by vitorgalvao** [comment]
The last active window is the one at the top. That’s already what the workflow does, it stacks them by whatever order they’re drawn. Windows in other virtual desktops aren’t included, as is explained in various places. This order is an explicit goal of the workflow and what most people want, so it will remain.

**Comment by adamnemecek** [comment]
I think I meant that all the windows would be sorted like that.

**Comment by vitorgalvao** [comment]
They are. All the visible ones. Getting others is not really viable.

**Comment by vitorgalvao** [comment]
It’s windows of all apps which are visible in the current Desktop.

If you have a specific issue, please be specific in the report. If you believe something is wrong with the order as it’s explained, please provide more details, including screenshots, or even better [a video](https://support.apple.com/en-us/HT208721). With information given piecemeal, it’s impossible for me to form a clear picture of what you’re asking.
