### ISSUE TITLE
Hotkey to quit an application

### ISSUE THREAD

**Issue by Yakitrak** [alfredapp/window-switcher-workflow#9]
### Feature details

Thank you for making this - It is a really nice window switcher. I was wondering if it is possible to to set a hotkey to quit an application. That's a common feature in other switchers that I have used and would make this more useful.

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

You don’t need this workflow to quit an application (and that’s out of scope), you can make it yourself by connecting a [Hotkey](https://www.alfredapp.com/help/workflows/triggers/hotkey/) to the [Automation Task](https://www.alfredapp.com/help/workflows/automations/automation-task/) to Quit Applications.

**Comment by Yakitrak** [comment]
Fair enough on it being out of scope, I've seen it in a similar workflow in Raycast and AltTab app also has this functionality so was hoping to replicate it here.

I have set an hotkey to this workflow, and I can see Automation Task has a section to quit an app but I don't see how I would link it to your workflow so the app currently with the cursor is quit. Would you please be able to explain a bit more?

**Comment by vitorgalvao** [comment]
I think I misunderstood. What you seem to want is a *modifier* to quit the app of whose window is highlighted in the Script Filter, correct?

[Like this](https://github.com/alfredapp/window-switcher-workflow/files/15015980/Window.Switcher.alfredworkflow.zip)? Press <kbd>⌘</kbd><kbd>↩</kbd>.

**Comment by Yakitrak** [comment]
Yes that's exactly what I was looking for, thanks! Only thing is it closes Alfred once you quit an application so you can't quit multiple or switch to a different window after quitting. But I guess that's just a limitation of Alfred.

**Comment by vitorgalvao** [comment]
It’s not a limitation, you can make it work like that by double clicking the connection and ticking the box to not close Alfred on actioning.

<img width="113" alt="image" src="https://github.com/alfredapp/window-switcher-workflow/assets/1699443/5fd54dbd-6e4f-4bcb-a821-77d57c355af7">

Though I’m not sure that’d be desirable for the official release. I’ll think about it. Either way, you can make the change in your local set up. Just remember that’ll be overwritten when you update the workflow, but this has been quite stable so further releases are unlikely.

**Comment by Yakitrak** [comment]
Ah, I see. That works but it doesn't refresh the items so it still keeps the closed app in the display. That's not a problem though. Thanks again for the help!
